### ISSUE TITLE
Add test cases from test project

### ISSUE THREAD

**Issue by pbiggar** [darklang/rescript-tea#14]
There's a test project over at https://github.com/OvermindDL1/bucklescript-testing. We should add the test code to our test suite. Some of it may already be there though.

**Comment by OceanOak** [comment]
Should I convert all the files inside src to rescript and add them to the rescript_tea test file?

**Comment by pbiggar** [comment]
Yes. First you'll need to take a look and see what exactly needs to be ported. We just want the sample app part. I think it's intermingled with the bucklescript-tea code in that repo, so you'll have to prise it apart a little bit, and probably make some adaptations.

**Comment by pbiggar** [comment]
Done.
