### ISSUE TITLE
Update starter kits

### ISSUE THREAD

**Issue by pbiggar** [darklang/rescript-tea#46]
There are some starter kits in the README, written by @tcoopman and @feluxe. They might convert these to use rescript-tea or instead we could offer alternatives.

**Comment by tcoopman** [comment]
Feel free to port them. I currently have no time nor interest to port these

**Comment by pbiggar** [comment]
@celsobonutti Wonderful, thank you! Assigned to you.

**Comment by celsobonutti** [comment]
@pbiggar I've created [celsobonutti/vite-template-rescript-tea](https://github.com/celsobonutti/vite-template-rescript-tea). Can you take a look if that's good enough? 
If it is, I'll create a PR to add it to this repo's README.

**Comment by pbiggar** [comment]
This looks great! I haven't tested it but I presume you have - I checked each file and it looks right.

**Comment by xudaotutou** [comment]
@celsobonutti You can automatically open Rescript Watch while using the Vite with the https://github.com/jihchi/vite-plugin-rescript.

**Comment by celsobonutti** [comment]
@xudaotutou thanks for the tip! Guess I've away from the ReScript community too long 🙈.
I'll update it!
