### ISSUE TITLE
fix counter.res in README.md

### ISSUE THREAD

**Issue by xudaotutou** [darklang/rescript-tea#50]
* There is missing right arrow in viewButton function
* The usage of variant Set is wrong in view function
* The Vdom module and the Events module are not founded

**Comment by pbiggar** [comment]
Wonderful, thanks! Are you able to put together a PR to fix it? Happy to help if you have questions.

**Comment by xudaotutou** [comment]
#51 
- I have updated the example program

**Comment by pbiggar** [comment]
Fixed in #51
